require('plugins')
require('base')
require('keymaps')

require('pluginsConfig.lineconfig')
require('pluginsConfig.theme')
require('pluginsConfig.icons')
require('pluginsConfig.filer')
require('pluginsConfig.git')
require('pluginsConfig.coc')
require('pluginsConfig.complete')
